# Death message configuration
death-message:
  display: true
  died: "{victim} died"
  
# The amount of time you will be in spectator mode for
# 20 ticks = 1 second
ticks: 100

# Teleport to the world spawnpoint when you respawn
teleport-to-spawn: true

