# Death message configuration
death-message:
  display: true
  died: "{victim} died"
  
# The amount of time you will be in spectator mode for (in seconds)
time: 5

# Teleport to the world spawnpoint when you respawn
teleport-to-spawn: true

