# The messages to be displayed when you 'die'
# {victim} {world} - & instead of ยง
death-message:
  display: true
  died: 
    player: "Oh noes! You will respawn soon."
    all: "{victim} died :("
  
# The amount of time you will be in spectator mode for (in seconds)
time: 5

# Teleport to the world spawnpoint when you 'respawn'
teleport-to-spawn: true

# Set teleport-to-spawn to false to use
teleport-to:
  x: 8
  y: 100
  z: 8

# Fire a PlayerDeathEvent when you 'die'
fire-death-event: false
